name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
          
    - name: Install and upgrade pip
      run: python -m pip install --upgrade pip
    
    - name: Install Python dependencies
      run: |
        pip install sphinx sphinx_rtd_theme sphinx-tabs sphinxext-opengraph doc8
        pip install -r requirements.txt
    
    - name: Check links
      run: make linkcheck
    
    - name: Check lint
      run: make lint
    
    - name: Compile HTML
      run: make html
